# Tune Linux Kernel
- name: set vm maximum map count
  command: bash -c "echo {{ vm_max_map_count }} > /proc/sys/vm/max_map_count"
  # ansible.posix.sysctl:
    # name: vm.max_map_count
    # value: '{{ vm_max_map_count }}'
    # state: present

- name: set fs file-max
  command: bash -c "echo {{ fs_file_max }} > /proc/sys/fs/file-max"
  # ansible.posix.sysctl:
  #   name: fs.file-max
  #   value: "{{ fs_file-max }}"
  #   state: present

####N.B: ansible-galaxy collection install community.general on ansible master
- name: configure system settings, max number of file descriptors and number of user processes
  community.general.pam_limits:
    domain: sonarqube
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: "{{ max_no_open_file_descriptors }}" }
    - { limit_type: '-', limit_item: 'nproc', value: "{{ max_no_of_user_processes }}" }
  notify: 
    - reload system settings

- name: apt update and upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: setup swap space
  shell: dd if=/dev/zero of=/swapfile bs=1M count=2048 ; chmod 0600 /swapfile ; mkswap /swapfile ; swapon /swapfile
  when: swap_status == "on"